#!/bin/env python3

import sys
import getpass
from iTTY import iTTY

def attempt_login(host):
    try:
        host = host.strip()
        tty = iTTY(host=host.strip(), username=username, password=password)
        if tty.login():
            if tty.shell:
                print(f'{host} reachable via SSH')
            elif tty.session:
                print(f'{host} reachable via TELNET')
            else:
                print(f'{host} not reachable')
    except:
        print(f'{host} not reachable')

if len(sys.argv) < 4:
    username = input("Username: ")
    password = getpass.getpass()
    host = input("Host: ")
else:
    username = sys.argv[1]
    password = sys.argv[2]
    host = sys.argv[3]

attempt_login(host)
