#!/usr/bin/env python3

import getpass, sys
from threading import Semaphore
from stringutils import StringUtils
from iTTY.mpcommandthread import Mpcommand

if len(sys.argv) < 5:
    username = input("Username: ")
    password = getpass.getpass()
    devicelist = input("Device list file: ")
else:
    username = sys.argv[1]
    password = sys.argv[2]
    devicelist = sys.argv[3]
hostnames = open(devicelist, 'r')
threadcount = 1000
commanddelay = 3
junos = ['show configuration snmp contact', ]
ios = ['show snmp contact']
xr = ['show run | in contact', ]
asa = ['enable', password, 'show run | in contact']
alu = ['admin display-config | match contact']
pool = Semaphore(threadcount)
threads = []
for host in hostnames:
    thread = Mpcommand(username, password, host, commanddelay, pool=pool, \
        junoscommands=junos, ioscommands=ios, xrcommands=xr, alucommands=alu, asacommands=asa, commandheader=0)
    threads.append(thread)
    thread.start()
report = [['Hostname', 'Owner'], ]
for t in threads: 
    t.join()
    try:
        report.append([t.host.strip(), t.tty.get_output()[-1].split()[-1].strip('"').strip(';').strip()])
    except:
        print("No data available for " + t.host.strip())
hostnames.close()
print(StringUtils.columnize(report, bars=1))
