#!/usr/bin/env python

import time, re, sys
from iTTY import iTTY
from iTTY.format import Format

tty = iTTY()
hour = 0
if len(sys.argv) < 4:
	tty.setlogin()
	tty.sethost(raw_input("Device: ").split('.', 1)[0])
	hour = raw_input('Time (24 hour clock): ')
else:
	tty.setlogin(username=sys.argv[1],password=sys.argv[2])
	tty.sethost(sys.argv[3])
	if len(sys.argv) > 4: hour = sys.argv[4]
if hour:
	if re.search('\:', hour): hour = "\:".join(hour.split(':'))
interface = ('GigE', 'ge-', 'te-', 'Te', 'Gi', 'Fa', 'ae', 'agg')
month = time.strftime('%b')
day = time.strftime('%d')
if int(day) < 10: day = month + "  " + day[-1]
else: day = month + " " + day
if hour: day = day + ' ' + hour
day = day.strip()
tty.setcommands(['terminal length 0', 'sh log | utility egrep -e \'' + day + '.*LINK-3-UPDOWN.*Down\''])
output = []
ssh = 0
if tty.securelogin():
	ssh = 1
	tty.runseccommands(25)
elif tty.unsecurelogin():
	tty.rununseccommands(25)
else: exit()
output = Format.siftoutput(tty.output)
tty.clearoutput()
tty.clearcommands()
flaps = []
for line in output: 
	if line.startswith("LC"):
		flaps.append(line.split(",")[0].split(" ")[-1])
report = set()
for y in flaps:
	count = len([x for x in flaps if x == y])
	report.add((y, count))
print '\n\nFLAPS  INTERFACE          ADMIN       OPER        DESCRIPTION'
print '--------------------------------------------------------------------------------------'
tty.setcommands(['sh int desc | ex admin'])
if ssh: tty.runseccommands(10)
else: tty.rununseccommands(10) 
interfaces = Format.siftoutput(tty.output)
for line in interfaces:
	li = line.split(' ')
	l = li[0][2:]
	for lin in report:
		intnum = lin[0].split('E')[-1]
		if re.search(intnum, l) and re.search(li[0][:1], lin[0]):
			if lin[1] < 10: print '    ' + str(lin[1]) + '  ' + line
			elif lin[1] < 100: print '   ' + str(lin[1]) + '  ' + line
			elif lin[1] < 1000: print '  ' + str(lin[1]) + '  ' + line
			elif lin[1] < 10000: print ' ' + str(lin[1]) + '  ' + line
			else: print str(lin[1]) + ' ' + line
			report.remove(lin)
			break
