#!/usr/bin/env python3

import sys
import getpass
import multiprocessing
from iTTY import iTTY

"""
Attempts only to login to devices (first via ssh, then via telnet)
Prints string determining whether and how it was able to login
"""

def attempt_login(host):
    try:
        host = host.strip()
        tty = iTTY(host=host.strip(), username=username, password=password)
        if tty.login():
            if tty.shell:
                print(f'{host} reachable via SSH')
            elif tty.session:
                print(f'{host} reachable via TELNET')
        else:
            print(f'{host} not reachable')
    except:
        print(f'{host} not reachable')

if len(sys.argv) < 4:
    username = input("Username: ")
    password = getpass.getpass()
    devicelist = input("Device list file: ")
else:
    username = sys.argv[1]
    password = sys.argv[2]
    devicelist = sys.argv[3]

with open(devicelist, 'r') as hosts:
    with multiprocessing.Pool(processes=multiprocessing.cpu_count() * 16) as pool:
        pool.map(attempt_login, hosts)
