#!/usr/bin/env python3

import sys
import re
import getpass
import time
import resource
import asyncio
import multiprocessing
from functools import partial
from iTTY import iTTY, CouldNotConnectError, BrokenConnectionError

"""
Attempts only to login to devices (first via ssh, then via telnet)
Prints string determining whether and how it was able to login
"""

def parse_params():
    username = ''
    password = ''
    device_list = []
    if len(sys.argv) > 1:
        for i, arg in enumerate(sys.argv):
            if arg == '-u':
                username = sys.argv[i+1]
            elif arg == '-p':
                password = sys.argv[i+1]
            elif arg == '-d':
                device_list = sys.argv[i+1]
    if not username:
        username = input("Username: ")
    if not password:
        password = getpass.getpass()
    if not device_list:
        device_list = input("Device list file: ")
    return (username, password, device_list)

async def attempt_login(host):
    global ssh
    global telnet
    global failed
    host = host.strip()
    try:
        async with iTTY(host=host.strip(), username=USERNAME, password=PASSWORD, timeout=10) as tty:
            login_method = tty.telnet_or_ssh()
            if login_method == 'SSH':
                with ssh.get_lock():
                    ssh.value += 1
            else:
                with telnet.get_lock():
                    telnet.value += 1
            print(f'{host} reachable via {login_method}')
    except CouldNotConnectError as e:
        with failed.get_lock():
            failed.value += 1
        for exception in e.exceptions.values():
            if re.search('Authentication', exception):
                print(f'authentication failed for {host}')
                return
        print(f'could not connect to {host}')

def get_devices(devicelist):
    devices = [[]]
    with open(devicelist, 'r') as hosts:
        hostnames = list(hosts)
        dev_count = len(hostnames)
        if dev_count > int(ULIMIT/CPUS):
            group_count = int(dev_count/int(ULIMIT/CPUS))
        else:
            group_count = CPUS
        for index, host in enumerate(hostnames):
            if index % group_count >= len(devices):
                devices.append([])
            devices[index % group_count].append(host.strip())
    return devices, dev_count

def verify(devices):
    loops = []
    loop = asyncio.new_event_loop()
    for device in devices:
        task = loop.create_task(attempt_login(device))
        loops.append(task)
    if loops:
        loop.run_until_complete(asyncio.wait(loops))

if __name__ == '__main__':
    global ssh
    global telnet
    global failed
    USERNAME, PASSWORD, DEVICELIST = parse_params()
    if not all((USERNAME, PASSWORD, DEVICELIST)):
        print('Need username, password, and devicelist to proceed')
        exit()
    CPUS = multiprocessing.cpu_count()
    ULIMIT = resource.getrlimit(resource.RLIMIT_NOFILE)[0] * 2
    DEVICES, DEV_COUNT = get_devices(DEVICELIST)
    if not DEVICES:
        print('Could not generate device list')
        exit()
    ssh = multiprocessing.Value('i', 0)
    telnet = multiprocessing.Value('i', 0)
    failed = multiprocessing.Value('i', 0)
    start = time.time()
    with multiprocessing.Pool(processes=CPUS, maxtasksperchild=1) as pool:
        pool.imap_unordered(verify, DEVICES)
        pool.close()
        pool.join()
    end = time.time()
    print('\n\n', '-' * 100, '\n\n')
    print(f'Successfully logged into {ssh.value + telnet.value} out of {DEV_COUNT} devices in {int((end - start)/60)} minutes and {int(end - start) % 60} seconds')
    print('\n', f'{ssh.value} devices were reachable via SSH. {telnet.value} devices were reachable via Telnet. There were {failed.value} failed attempts.', '\n')
